apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: advanced-chaos-workflow
  namespace: default
spec:
  entry: the-entry
  templates:
    - name: the-entry
      templateType: Serial
      deadline: 12m
      children:
        - workflow-pod-failure
        - workflow-recovery-1
        - workflow-disk-io-stress
        - workflow-recovery-2
        - workflow-cpu-stress
        - workflow-recovery-3
    
    - name: workflow-pod-failure
      templateType: PodChaos
      deadline: 90s
      podChaos:
        action: pod-failure
        mode: one
        selector:
          namespaces:
            - default
          labelSelectors:
            "app.kubernetes.io/name": "webapp"
        duration: "30s"
    
    - name: workflow-disk-io-stress
      templateType: IOChaos
      deadline: 2m
      ioChaos:
        action: mixed-random
        mode: all
        selector:
          namespaces:
            - default
          labelSelectors:
            "app.kubernetes.io/name": "webapp"
        volumePath: /var/run/secrets
        path: "/var/run/secrets/**/*"
        duration: "60s"
        delay: "50ms"
        percent: 50
    
    - name: workflow-cpu-stress
      templateType: StressChaos
      deadline: 2m
      stressChaos:
        mode: all
        selector:
          namespaces:
            - default
          labelSelectors:
            "app.kubernetes.io/name": "webapp"
        stressors:
          cpu:
            workers: 2
            load: 80
        duration: "60s"
    
    - name: workflow-recovery-1
      templateType: Suspend
      deadline: 45s
      suspend:
        duration: "30s"
    
    - name: workflow-recovery-2
      templateType: Suspend
      deadline: 45s
      suspend:
        duration: "30s"
    
    - name: workflow-recovery-3
      templateType: Suspend
      deadline: 45s
      suspend:
        duration: "30s"

