apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-experiment
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app.kubernetes.io/name": "webapp"
  duration: "60s"
  stressors:
    cpu:
      workers: 2
      load: 80

