apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: disk-io-stress
  namespace: default
spec:
  action: mixed-random
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app.kubernetes.io/name": "webapp"
  volumePath: /var/run/secrets
  path: "/var/run/secrets/**/*"
  duration: "60s"
  percent: 50
  delay: "10ms"
