apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-experiment
  namespace: default
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: webapp
  delay:
    latency: "500ms"
    correlation: "50"
    jitter: "100ms"
  duration: "120s"
  direction: to
