apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: nginx-container-kill
  namespace: default
spec:
  action: container-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app.kubernetes.io/name": "webapp"
  duration: "15s"
  containerNames:
    - nginx
