apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: nginx-disk-io-delay
  namespace: default
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app.kubernetes.io/name": "webapp"
  volumePath: /var/run/secrets
  path: "/var/run/secrets/**/*"
  duration: "60s"
  delay: "100ms"
  percent: 50
