apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: nginx-combined-stress
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app.kubernetes.io/name": "webapp"
  duration: "90s"
  stressors:
    cpu:
      workers: 1
      load: 60
    memory:
      workers: 1
      size: "32Mi"
  containerNames:
    - nginx
