apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-experiment
  namespace: default
spec:
  action: pod-failure
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - default
    labelSelectors:
      app: webapp
  scheduler:
    cron: "@every 5m"
